### ISSUE TITLE
Runtime comparison

### ISSUE THREAD

**Issue by Samuel-Ranellucci** [ZenGo-X/gotham-city#8]
Dear KZen members,

We noticed that you compared the run times of your repository with our blockchain-crypto-mpc repository. In your code we see that you use multi-threading, so we updated our library to use multi-threading as well. This change should provide a more “apples-to-apples” comparison.
 
We also added a benchmarking tool for our algorithms that, we feel, provides a more accurate measurement of the run time.
 
We kindly suggest you run the tests again – we are interested in seeing the results.

Best Regards,

Dr. Samuel Ranellucci
Cryptographer, Unbound Tech

**Comment by omershlo** [comment]
Hi Samuel, 

Thank you very much for opening this issue. 
We re-run benchmarks (using our tool since we couldn't work with yours) and updated the numbers accordingly.  Indeed, blockchain-crypto-mpc 2P-ecdsa-keygen is now much faster, achieving better performance than gotham-city.  
We will keep you updated on future changes and additions to the benchmark table.

**Comment by Samuel-Ranellucci** [comment]
Dear Kzen Members,

We added a Python script that can be used for accurate testing. It can be found at:
https://github.com/unbound-tech/blockchain-crypto-mpc/tree/master/python

We also updated the build instructions for the C++ benchmark tool with the commands 
needed to run the tool from a clean installation of Ubuntu.

Thank you for your time.

Best Regards,

Dr. Samuel Ranellucci
Cryptographer, Unbound Tech
